[options]
wallpaper = "~/Pictures/wallpapers/wp.png"

[variables]
font_name = "Iosevka"
font_size = "10"

[entries]
dunst    = [ { target = "./configs/dunst/dunstrc",    template = "./templates/dunstrc",       dest = "~/.config/dunst/dunstrc"  } ]
foot     = [ { target = "./configs/foot/foot.ini",    template = "./templates/foot.ini",      dest = "~/.config/foot/foot.ini"  } ]
nvim     = [ { target = "./configs/nvim/init.lua",    template = "./templates/nvim-init.lua", dest = "~/.config/nvim/init.lua"  } ]
starship = [ { target = "./configs/starship.toml",    template = "./templates/starship.toml", dest = "~/.config/starship.toml"  } ]
sway     = [ { target = "./configs/sway/config",      template = "./templates/sway-config",   dest = "~/.config/sway/config"    } ]
tmux     = [ { target = "./configs/tmux/tmux.conf",   template = "./templates/tmux.conf",     dest = "~/.config/tmux/tmux.conf" } ]
wmenu    = [ { target = "./bin/wmenu-custom",         template = "./templates/wmenu-custom",  dest = "~/bin/wmenu-custom"       } ]

firefox  = [ { target = "./configs/firefox/user.js",  dest = "~/.config/mozilla/firefox/khsaad/user.js" } ]
fish     = [ { target = "./configs/fish/config.fish", dest = "~/.config/fish/config.fish"               } ]
git      = [ { target = "./configs/git/config",       dest = "~/.config/git/config"                     } ]
ripgrep  = [ { target = "./configs/ripgreprc",        dest = "~/.config/ripgreprc"                      } ]

bins  = [ { target = "./bin",            dest = "~/bin",            recursive = true } ]
fcitx = [ { target = "./configs/fcitx5", dest = "~/.config/fcitx5", recursive = true } ]
yazi  = [ { target = "./configs/yazi",   dest = "~/.config/yazi",   recursive = true } ]

gtk = [
    { target = "./configs/gtk/gtk.css", template = "templates/gtk.css", dest = "~/.config/gtk-3.0/gtk.css" },
    { target = "./configs/gtk/gtk.css", template = "templates/gtk.css", dest = "~/.config/gtk-4.0/gtk.css" },
]

waybar = [
    { target   = "./configs/waybar",             dest = "~/.config/waybar", recursive = true },
    { template = "./templates/waybar-style.css", dest = "~/.config/waybar/style.css"         },
]
